/*
 * control.java
 *
 * Created on 5. November 2003, 15:56
 */

package GUI;

/**
 *
 * @author  2fast
 */
public class control extends javax.swing.JFrame {
    private video   empfangsfenster=null;
    private chat    chatfenster=null;
    /** Creates new form control */
    public control() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setTitle("Kontrollfeld");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jPanel1.setLayout(new java.awt.GridLayout(8, 0, 0, 5));

        jButton1.setText("Empfangsfenster");
        jButton1.setBorder(null);
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                control.this.actionPerformed(evt);
            }
        });

        jPanel1.add(jButton1);

        jButton2.setText("Sendefenster");
        jButton2.setBorder(null);
        jButton2.setFocusPainted(false);
        jPanel1.add(jButton2);

        jButton3.setText("Chatfenster");
        jButton3.setBorder(null);
        jButton3.setFocusPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                control.this.actionPerformed(evt);
            }
        });

        jPanel1.add(jButton3);

        jButton4.setText("Optionen");
        jButton4.setBorder(null);
        jButton4.setFocusPainted(false);
        jPanel1.add(jButton4);

        jButton5.setText("Kontakte");
        jButton5.setBorder(null);
        jButton5.setFocusPainted(false);
        jPanel1.add(jButton5);

        jButton6.setText("Hilfe");
        jButton6.setBorder(null);
        jButton6.setFocusPainted(false);
        jPanel1.add(jButton6);

        jButton7.setText("direkte Verbindung");
        jButton7.setBorder(null);
        jButton7.setFocusPainted(false);
        jPanel1.add(jButton7);

        jButton8.setText("Auflegen");
        jButton8.setBorder(null);
        jButton8.setFocusPainted(false);
        jPanel1.add(jButton8);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jMenu2.setText("Datei");
        jMenuItem1.setText("Beenden");
        jMenuItem1.setBorder(null);
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                control.this.actionPerformed(evt);
            }
        });

        jMenu2.add(jMenuItem1);

        jMenuBar2.add(jMenu2);

        setJMenuBar(jMenuBar2);

        pack();
    }//GEN-END:initComponents

    private void actionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionPerformed
        String cmd = evt.getActionCommand();
        
        if(cmd == "Beenden") System.exit(0);
        else if(cmd == "Empfangsfenster") {
            if(empfangsfenster == null) empfangsfenster = new video();
            empfangsfenster.show();
        }
        else if(cmd == "Chatfenster"){
            if(chatfenster == null) chatfenster = new chat();
            chatfenster.show();
        }
    }//GEN-LAST:event_actionPerformed
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new control().show();
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    
}
