package movas.GUI;

/*
 * HilfeFenster.java
 *
 * Created on 8. Februar 2004, 10:50
 */

/**
 *
 * @author  MS
 */
public class HilfeFenster extends javax.swing.JFrame {
    
    private static String empfangsfenster="file://localhost/D:/empfangsfenster.html";
    private static String sendefenster="file://localhost/D:/empfangsfenster.html";
    private static String optionfenster="file://localhost/D:/empfangsfenster.html";
    private static String chatfenster="file://localhost/D:/empfangsfenster.html";
    private static String verbindungfenster="file://localhost/D:/empfangsfenster.html";
    private static String hilfefenster="file://localhost/D:/empfangsfenster.html";
    private static String auflegenfenster="file://localhost/D:/empfangsfenster.html";
    private static String kontaktfenster="file://localhost/D:/empfangsfenster.html";
    private static String startfenster=hilfefenster;
    
    /** Creates new form HilfeFenster */
    public HilfeFenster() {
        initComponents();
        jEditorPane1.setContentType("text/html");
        try {
            jEditorPane1.setPage(startfenster);
        } catch (Exception e) {}
         this.setLocation((java.awt.Toolkit.getDefaultToolkit().getScreenSize().width/2)-(this.getWidth()/2),
        (java.awt.Toolkit.getDefaultToolkit().getScreenSize().height/2)-(this.getHeight()/2));
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();

        setTitle("Hilfe");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jPanel1.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setViewportView(jEditorPane1);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.GridLayout(9, 1));

        jLabel1.setFont(new java.awt.Font("Dialog", 3, 18));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Hilfe zu:");
        jPanel2.add(jLabel1);

        jButton1.setMnemonic('e');
        jButton1.setText("Empfangsfenster");
        jButton1.setToolTipText("Empfangsfenster \u00f6ffnen");
        jButton1.setBorder(new javax.swing.border.BevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActionPerformed(evt);
            }
        });

        jPanel2.add(jButton1);

        jButton2.setMnemonic('s');
        jButton2.setText("Sendefenster");
        jButton2.setToolTipText("Video Sendefenster \u00f6ffnen");
        jButton2.setBorder(new javax.swing.border.BevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.setFocusPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActionPerformed(evt);
            }
        });

        jPanel2.add(jButton2);

        jButton3.setMnemonic('c');
        jButton3.setText("Chatfenster");
        jButton3.setToolTipText("Text-Chat Fenster \u00f6ffnen");
        jButton3.setBorder(new javax.swing.border.BevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.setFocusPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActionPerformed(evt);
            }
        });

        jPanel2.add(jButton3);

        jButton4.setMnemonic('o');
        jButton4.setText("Optionen");
        jButton4.setToolTipText("Einstellungsfenster \u00f6ffnen");
        jButton4.setBorder(new javax.swing.border.BevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton4.setFocusPainted(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActionPerformed(evt);
            }
        });

        jPanel2.add(jButton4);

        jButton5.setMnemonic('k');
        jButton5.setText("Kontakte");
        jButton5.setToolTipText("Telefonbuch \u00f6ffnen");
        jButton5.setBorder(new javax.swing.border.BevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton5.setFocusPainted(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActionPerformed(evt);
            }
        });

        jPanel2.add(jButton5);

        jButton6.setMnemonic('h');
        jButton6.setText("Hilfe");
        jButton6.setToolTipText("Hilfe anzeigen");
        jButton6.setBorder(new javax.swing.border.BevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton6.setFocusPainted(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActionPerformed(evt);
            }
        });

        jPanel2.add(jButton6);

        jButton7.setMnemonic('v');
        jButton7.setText("direkte Verbindung");
        jButton7.setToolTipText("eine direkte Verbindung anw\u00e4hlen");
        jButton7.setBorder(new javax.swing.border.BevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton7.setFocusPainted(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActionPerformed(evt);
            }
        });

        jPanel2.add(jButton7);

        jButton8.setMnemonic('b');
        jButton8.setText("Beenden");
        jButton8.setToolTipText("aktuelle Verbindung beenden");
        jButton8.setBorder(new javax.swing.border.BevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton8.setFocusPainted(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActionPerformed(evt);
            }
        });

        jPanel2.add(jButton8);

        getContentPane().add(jPanel2, java.awt.BorderLayout.WEST);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-500)/2, (screenSize.height-400)/2, 500, 400);
    }//GEN-END:initComponents

    private void ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActionPerformed
        // Add your handling code here:
        try {
            if (evt.getActionCommand().equals("Empfangsfenster"))jEditorPane1.setPage(empfangsfenster);
            else if (evt.getActionCommand().equals("Sendefenster"))jEditorPane1.setPage(sendefenster);
            else if (evt.getActionCommand().equals("Chatfenster"))jEditorPane1.setPage(chatfenster);
            else if (evt.getActionCommand().equals("Optionen"))jEditorPane1.setPage(optionfenster);
            else if (evt.getActionCommand().equals("Kontakte"))jEditorPane1.setPage(kontaktfenster);
            else if (evt.getActionCommand().equals("Hilfe"))jEditorPane1.setPage(hilfefenster);
            else if (evt.getActionCommand().equals("direkt Verbindung"))jEditorPane1.setPage(verbindungfenster);
            else if (evt.getActionCommand().equals("Auflegen"))jEditorPane1.setPage(auflegenfenster);
        } catch (Exception ex) {ex.printStackTrace();}
    }//GEN-LAST:event_ActionPerformed
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        this.hide();
    }//GEN-LAST:event_exitForm
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new HilfeFenster().show();
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    
}
