/*
 * video.java
 *
 * Created on 5. November 2003, 17:17
 */

package movas.GUI;

/**
 *
 * @author  2fast
 */
public class video extends javax.swing.JFrame {
    
    private int typ; 
    
    public static final int EMPFANG=0;
    public static final int VERSAND=1;
    
    /** Creates new form video */
    public video() {
        initComponents();
        JPanelInitVideo=new movas.Init.InitVideo();
        this.getContentPane().add(JPanelInitVideo);
        this.repaint();
    }
    
    public video(int typ){
        initComponents();
        this.typ = typ;
        this.getContentPane().add(new movas.Init.InitVideo());
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jToolBar1 = new javax.swing.JToolBar();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanelVideo = new javax.swing.JPanel();

        setName("Videoframe");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setText("Sie sind mit bla verbunden");
        jPanel1.add(jLabel1, java.awt.BorderLayout.CENTER);

        jButton1.setText("Ausblenden");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActionPerformed(evt);
            }
        });

        jPanel1.add(jButton1, java.awt.BorderLayout.EAST);

        jToolBar1.add(jPanel1);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.SOUTH);

        getContentPane().add(jPanelVideo, java.awt.BorderLayout.CENTER);

        pack();
    }//GEN-END:initComponents

    private void ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActionPerformed
        String cmd = evt.getActionCommand();
        if(cmd == "Ausblenden") this.setVisible(false);
    }//GEN-LAST:event_ActionPerformed
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        this.setVisible(false);
       ((movas.Init.InitVideo)JPanelInitVideo).stop(); 
    }//GEN-LAST:event_exitForm
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new video().show();
    }
    
    private javax.swing.JPanel JPanelInitVideo;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelVideo;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
    
}
